export const coursesArr = [
  {
    id: 1,
    title: "Introduction to Data Science",
    description: "Learn the fundamentals of data science and analysis.",
    imageUrl:
      "https://answersq.com/wp-content/uploads/2022/12/free-data-science-courses.webp",
    watchHours: 20,
    actualWatchHours: 15,
    totalReviews: 10,
    category: ["Data Science", "Technology"],
    upVotes: 20,
    downVotes: 80,
    url: "https://example.com/intro-to-data-science",
    clicksReceived: 200,
    isSponsored: true,
    publisherId: "publisher123",
    reviews: [
      {
        author: "JohnDoe",
        description: "Great course! Very informative and well-structured.",
        profilePic: "https://randomuser.me/api/portraits/men/16.jpg",
        likeCount: 10,
        username: "john_doe123",
        createdAt: "2024-04-22T09:15:30.000Z",
      },
      {
        author: "JaneSmith",
        description:
          "I found this course to be a fantastic introduction to data science. Highly recommended.",
        profilePic: "https://randomuser.me/api/portraits/men/50.jpg",
        likeCount: 20,
        username: "jane_smith89",
        createdAt: "2024-04-20T12:45:10.000Z",
      },
      {
        author: "DataGeek123",
        description:
          "The content was comprehensive and easy to understand. A must for beginners!",
        profilePic: "https://randomuser.me/api/portraits/men/34.jpg",
        likeCount: 15,
        username: "data_geek_123",
        createdAt: "2024-04-18T16:30:20.000Z",
      },
      {
        author: "TechEnthusiast",
        description:
          "Excellent course! Covered all the basics of data science thoroughly.",
        profilePic: "https://randomuser.me/api/portraits/men/40.jpg",
        likeCount: 18,
        username: "tech_enthusiast56",
        createdAt: "2024-04-16T08:20:05.000Z",
      },
      {
        author: "AnalyticsPro",
        description:
          "Really enjoyed this course. It provided a solid foundation for further learning.",
        profilePic: "https://randomuser.me/api/portraits/men/44.jpg",
        likeCount: 25,
        username: "analytics_pro",
        createdAt: "2024-04-14T14:10:45.000Z",
      },
      {
        author: "Coder123",
        description:
          "The examples and exercises were very helpful in grasping the concepts. Well done!",
        profilePic: "https://randomuser.me/api/portraits/men/16.jpg",
        likeCount: 12,
        username: "coder_123",
        createdAt: "2024-04-12T10:25:55.000Z",
      },
      {
        author: "BigDataFan",
        description:
          "As someone new to data science, I found this course incredibly useful. Thank you!",
        profilePic: "https://randomuser.me/api/portraits/men/50.jpg",
        likeCount: 17,
        username: "big_data_fan2000",
        createdAt: "2024-04-10T18:40:30.000Z",
      },
      {
        author: "Statistician101",
        description:
          "Clear explanations and practical examples make this course highly valuable.",
        profilePic: "https://randomuser.me/api/portraits/men/34.jpg",
        likeCount: 22,
        username: "statistician_101",
        createdAt: "2024-04-08T11:35:20.000Z",
      },
      {
        author: "DataExplorer",
        description:
          "The instructor did a great job explaining complex topics in a simple manner. Thumbs up!",
        profilePic: "https://randomuser.me/api/portraits/men/40.jpg",
        likeCount: 30,
        username: "data_explorer_007",
        createdAt: "2024-04-06T09:50:15.000Z",
      },
      {
        author: "LearningIsFun",
        description:
          "I've learned so much from this course. Can't wait to dive deeper into data science!",
        profilePic: "https://randomuser.me/api/portraits/men/44.jpg",
        likeCount: 28,
        username: "learning_is_fun",
        createdAt: "2024-04-04T15:55:10.000Z",
      },
    ],
  },
  {
    id: 2,
    title: "Beginner's Guide to Python",
    description: "Start your programming journey with Python.",
    imageUrl: "https://example.com/beginners-python.jpg",
    watchHours: 10,
    actualWatchHours: 8,
    totalReviews: 30,
    category: ["Programming", "Python"],
    upVotes: 80,
    downVotes: 2,
    url: "https://example.com/beginners-python",
    clicksReceived: 150,
    isSponsored: false,
    publisherId: "publisher456",
    reviews: [
      {
        author: "PythonLearner42",
        description:
          "This course was incredibly helpful for beginners like me. I learned a lot about Python programming and its basics.",
        profilePic: "https://randomuser.me/api/portraits/men/16.jpg",
        likeCount: 10,
        username: "pythonlearner42",
        createdAt: "2024-02-12T08:30:45.000Z",
      },
      {
        author: "CodeExplorer99",
        description:
          "As someone new to Python, I found this course to be a perfect introduction. The concepts were explained clearly, making it easy to understand.",
        profilePic: "https://randomuser.me/api/portraits/men/50.jpg",
        likeCount: 20,
        username: "codeexplorer99",
        createdAt: "2024-03-05T15:20:12.000Z",
      },
      {
        author: "PythonEnthusiast123",
        description:
          "I thoroughly enjoyed learning Python through this course. It covered all the basics in a structured manner, making it easy to follow along.",
        profilePic: "https://randomuser.me/api/portraits/men/34.jpg",
        likeCount: 15,
        username: "pythonenthusiast123",
        createdAt: "2024-03-20T10:45:30.000Z",
      },
      {
        author: "TechPythonMaster",
        description:
          "Excellent course for beginners! It provided a solid foundation in Python programming and helped me build confidence in my coding skills.",
        profilePic: "https://randomuser.me/api/portraits/men/40.jpg",
        likeCount: 18,
        username: "techpythonmaster",
        createdAt: "2024-02-28T18:10:55.000Z",
      },
      {
        author: "PythonNinja77",
        description:
          "This course made learning Python fun and engaging. I particularly enjoyed the hands-on exercises that helped reinforce the concepts.",
        profilePic: "https://randomuser.me/api/portraits/men/44.jpg",
        likeCount: 25,
        username: "pythonninja77",
        createdAt: "2024-02-10T09:05:20.000Z",
      },
      {
        author: "CodeWizard2023",
        description:
          "I found this course to be an excellent starting point for anyone interested in Python programming. The instructor's explanations were clear and easy to follow.",
        profilePic: "https://randomuser.me/api/portraits/men/16.jpg",
        likeCount: 12,
        username: "codewizard2023",
        createdAt: "2024-03-15T14:55:40.000Z",
      },
      {
        author: "PythonRookie2000",
        description:
          "As a beginner in Python, I found this course to be extremely valuable. It provided a step-by-step guide to learning the language, making it accessible for newcomers.",
        profilePic: "https://randomuser.me/api/portraits/men/50.jpg",
        likeCount: 17,
        username: "pythonrookie2000",
        createdAt: "2024-02-19T11:40:25.000Z",
      },
      {
        author: "PythonGuru55",
        description:
          "Clear explanations and practical examples make this course highly valuable for beginners in Python programming.",
        profilePic: "https://randomuser.me/api/portraits/men/34.jpg",
        likeCount: 22,
        username: "pythonguru55",
        createdAt: "2024-03-01T13:20:18.000Z",
      },
      {
        author: "CodeNerd9001",
        description:
          "The instructor did an excellent job of breaking down complex Python concepts into simple, understandable lessons. I would highly recommend this course to anyone starting out with Python.",
        profilePic: "https://randomuser.me/api/portraits/men/40.jpg",
        likeCount: 30,
        username: "codenerd9001",
        createdAt: "2024-02-23T17:30:10.000Z",
      },
      {
        author: "PythonLover2001",
        description:
          "I've learned so much from this course! It's reignited my passion for coding, and I'm excited to continue exploring Python.",
        profilePic: "https://randomuser.me/api/portraits/men/44.jpg",
        likeCount: 28,
        username: "pythonlover2001",
        createdAt: "2024-02-14T20:15:05.000Z",
      },
    ],
  },
  {
    id: 3,
    title: "Mastering JavaScript",
    description: "Become a JavaScript expert with comprehensive lessons.",
    imageUrl: "https://example.com/mastering-javascript.jpg",
    watchHours: 25,
    actualWatchHours: 20,
    totalReviews: 70,
    category: ["Programming", "JavaScript"],
    upVotes: 120,
    downVotes: 8,
    url: "https://example.com/mastering-javascript",
    clicksReceived: 250,
    isSponsored: true,
    publisherId: "publisher789",
    reviews: [],
  },
  {
    id: 4,
    title: "Artificial Intelligence Essentials",
    description:
      "Discover the essentials of artificial intelligence and machine learning.",
    imageUrl: "https://example.com/ai-essentials.jpg",
    watchHours: 15,
    actualWatchHours: 12,
    totalReviews: 40,
    category: ["Artificial Intelligence", "Technology"],
    upVotes: 90,
    downVotes: 3,
    url: "https://example.com/ai-essentials",
    clicksReceived: 180,
    isSponsored: false,
    publisherId: "publisher101",
    reviews: [],
  },
  {
    id: 5,
    title: "Web Development Bootcamp",
    description: "Learn full-stack web development from scratch.",
    imageUrl: "https://example.com/web-dev-bootcamp.jpg",
    watchHours: 30,
    actualWatchHours: 25,
    totalReviews: 80,
    category: ["Web Development", "Programming"],
    upVotes: 150,
    downVotes: 10,
    url: "https://example.com/web-dev-bootcamp",
    clicksReceived: 300,
    isSponsored: true,
    publisherId: "publisher202",
    reviews: [],
  },
];
